### ISSUE TITLE
Sette opp prod. keys

### ISSUE THREAD

**Issue by raae** [bGraphic/varsom-parse#16]

**Comment by raae** [comment]
Husker ikke selv hva jeg ville med dette, husker du @kjellivar?

**Comment by kjellivar** [comment]
Nei ikke helt sikker på det... Hvis det er app-keysene som blir brukt i ionic/parse i hybridappen, så er det tatt ut i egen fil som ikke er sjekket inn.

**Comment by raae** [comment]
Da stenger jeg denne.
